language: rust
cache:
  cargo: true
os:
  - linux
  - osx
rust:
  - nightly
services:
  - docker
before_deploy: "./tools/build-release rssbot ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: DNi7KnMkYZWm/5zD4ITvalxjnWKU/K0i2gkgooWvJJ/RXAHG89FxyT5/LlX8HtNEqYG38tp7IjQcttqiRXs7ciQyFo2g99fesuxKdXXBTa9oAHZaPNNJ5rydEQRFKmm2EnLkQcmOV/Wsifq5zBD17ixXyXIWGxZ2QRk/zk4yLQkxn2LPX0kM/9iKotPCfVJJcZ6WXYtQsizn7pbp1Ot+vpzspRQ6KkY/h9kv183K6WvEewMvsGANONTfKgiZyZ0vBBo/IRwYKJDmSbpz/RsFcrHb8Nk501jroM2ooFpb8K0jP6F5sEijac8Dc7MYJAr5q3FmdkcqbEUvV9NM39HUXTtJuL8CC01T+Jq99HijGE+fJ7GMjZEU+pprhoq6V17IUEk80TKXfznOXxNoR5DhJYQzFU47UsNDRlq64RXCmp7gFbZLEJXWVwULppbNdeKnmmNjOxfjtN9UsJTuWp6sn+2C33aOYvkDq+e5ZJlih1+VKj0Pp02GeQFpwFZd0Xmgg9aMyo1HvzhEJihb4EkJoYMCghLHjHDxewy+9cD+NhbRMtdrP+fZu+N6IqZpKrDZ8WElP66HJnbejuzMB9Ue8YZbYTJ6ek/avXfh6D93H04GcQv1pEHI9WknqOKB35nTGTd85eA4HRs+K78L0VB1us92fLZtbpUlc+RL1CGXvBc=
  file_glob: true
  file: "rssbot-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: iovxw/rssbot
    tags: true
